### ISSUE TITLE
[Discussion] Mockups edit image size

### ISSUE THREAD

**Issue by StefWe** [ubports/ubuntu-ui-extras#32]
I would like to implement a option to scale an image.

1. What icon we should place in the edit bar?

![grafik](https://user-images.githubusercontent.com/35935077/56136154-7a1b8a80-5f92-11e9-8129-ab8dc4ca5032.png)

2. Second question is how the User can make some input? Easy is a slider from 100% to maybe 10% or so?

![grafik](https://user-images.githubusercontent.com/35935077/56136418-0d54c000-5f93-11e9-8fbe-ac060118c556.png)

Maybe someone on the UX team can help? @cibersheep

**Comment by cibersheep** [comment]
Hi:
1) I would say nonsage of what the action is doing. So, instead of Fertig, I would say Scale. Abbrechen is good :)e of them as they already have a meaning. You might want to create one for that specific use ;)

2) Slider sounds good and intuitive

Bonus:

 About the buttons, have in mind that we usually:
 - color the main action (red if it's destructive, green if positive) but avoid coloring both.
 - Make clear message of what the action is doing. So, instead of Fertig, I would say Scale. Abbrechen is good :)
 - Main action goes to the right (or top) so I suggest: [neutral color Abbrechen] [green color Scale] order

**Comment by StefWe** [comment]
Thank you very much for the explanation and ideas.

The pictures above are examples from the expose function which is now available in the gallery edit bar.

For the scale function i only have a proof of concept, but nothing more.

I don't have the skills to create an icon, should I ask in the forum if anyone wants to help?

Some samples i found on the internet:
1. https://www.flaticon.com/free-icon/scale_232347
2. https://www.flaticon.com/free-icon/scale-circular-button_56444
3. https://www.freepik.com/free-icon/scaling-ios-7-interface-symbol_746816.htm

Any other ideas welcome.

**Comment by cibersheep** [comment]
Ouh. I like some of the 2. I think in some days I could send you something. Would you mind pinging me again some days (just in case I forget). Grgrgrl :)

**Comment by StefWe** [comment]
I'd be so happy for your help with the icon.

**Comment by cibersheep** [comment]
What do you think about this: 
![imatge](https://user-images.githubusercontent.com/6640041/56529514-2213f380-6551-11e9-850d-b82413d99c42.png)

**Comment by cibersheep** [comment]
[resize.zip](https://github.com/ubports/ubuntu-ui-extras/files/3104833/resize.zip)

**Comment by StefWe** [comment]
Thank you very much for your work. I like the icon very much. Think you can see that this is about scaling.
![screenshot20190424_230158723](https://user-images.githubusercontent.com/35935077/56693812-a5fee480-66e5-11e9-9e25-bc1d269baee7.png)
What do you think about making the lines white just like on the other icons?
Maybe draw the lines a little thicker?

**Comment by cibersheep** [comment]
Oh, nice. Yes: thicker lines (I must have forgotten :D sorry)

**Comment by cibersheep** [comment]
Ouh... real life dragged me... I'll do the changes today (sorry about that)

**Comment by StefWe** [comment]
Please don't get stressed out. I am very grateful for your help, but there is no hurry!

**Comment by cibersheep** [comment]
Ok, I checked and I actually had it at the correct size :| so... would you mind checking this? I didn't optimize it so it should behave as the rest...

[resize2.zip](https://github.com/ubports/ubuntu-ui-extras/files/3131096/resize2.zip)

**Comment by Keneda-ut** [comment]
Any update here?

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/lomiri-ui-extras/-/issues/32

Sorry for your inconvenience.
